language: node_js
sudo: false
node_js:
  - 6
deploy:
  - provider: npm
    api_key: ${NPM_API_KEY}
    email: ${NPM_EMAIL_ADDRESS}
    skip_cleanup: true
    on:
      repo: ezypeeze/react-mozer
      tags: true
